version: '3.3'
networks:
  net-mhpasswordmanager-mode-localhost:
    driver: bridge
services:
  config-services:
    image: docker.io/marcoshssilvadev/mhpasswordmanager-config-services
    env_file:
      - envs/config-services.env
    networks:
      - net-mhpasswordmanager-mode-localhost
    ports:
      - "8888:8888"
