networks:
  net:
    driver: bridge
services:
  configserver:
    image: docker.io/marcoshssilvadev/mhpasswordmanager-config-services
    env_file:
      - envs/config-services.env
    networks:
      - net
    ports:
      - "8888:8888"
