version: '3.3'
networks:
  net-mhpasswordmanager-mode-localhost:
    driver: bridge
services:
  config-services:
    image: nx-registry.marcoshssilva.com.br/jenkins-builds/amd64/password-manager/mhpasswordmanager-config-services:latest
    env_file:
      - envs/config-services.env
    networks:
      - net-mhpasswordmanager-mode-localhost
    ports:
      - "8888:8888"
