oauth-config-starter:
  users:

    - username: admin
      password: P@ssword123
      roles:
      - USER
      - ADMIN
      - MASTER
      accountNonExpired: true
      accountNonLocked: true
      credentialsNonExpired: true
      enabled: true

    - username: anonymous
      password: P@ssword123
      roles:
        - USER
      accountNonExpired: true
      accountNonLocked: true
      credentialsNonExpired: true
      enabled: true

  clients:
    - clientName: 'Registered client for PWA Client'
      clientId: MHPasswordManager
      clientSecret: b07968bd-8989-4f10-82c7-3e427e22c924
      authenticationMethod: CLIENT_SECRET_BASIC
      authenticationGrantTypes:
        - AUTHORIZATION_CODE
        - REFRESH_TOKEN
      redirectUris:
        - http://127.0.0.1:8080/mypass-manager/auth/swagger-ui/redirect
        - http://127.0.0.1:8080/mypass-manager/emails/swagger-ui/redirect
        - http://127.0.0.1:8080/mypass-manager/files/swagger-ui/redirect
        - http://127.0.0.1:8080/mypass-manager/passwords/swagger-ui/redirect
        - http://127.0.0.1:8080/mypass-manager/users/swagger-ui/redirect
        - http://127.0.0.1:8080/mypass-manager/client/authorize
        - https://oauth.pstmn.io/v1/callback
        - https://oidcdebugger.com/debug
      scopes:
        - 'openid'
        - 'profile'
        - 'email'
      tokenSettings:
        durationInMillis: 900000
        reuseRefreshToken: false
        refreshTokenTimeToLiveInMillis: 10800000
      clientSettings:
        requireAuthorizationConsent: true
        requireProofKey: false

    - clientName: 'Registered client for Client Credentials'
      clientId: MHPasswordManager-GlobalAdmin
      clientSecret: 9f45dc98-8e4f-11ee-b9d1-0242ac120002
      authenticationMethod: CLIENT_SECRET_BASIC
      authenticationGrantTypes:
        - CLIENT_CREDENTIALS
      scopes:
        - 'global:fullAccess'
      tokenSettings:
        durationInMillis: 180000

springdoc:
  show-actuator: true
  show-login-endpoint: false 
  swagger-ui:
    oauth2-authorization-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/authorize
    oauth2-token-url: http://127.0.0.1:8080/mypass-manager/auth/oauth2/token
    oauth:
      client-id: MHPasswordManager
      client-secret: b07968bd-8989-4f10-82c7-3e427e22c924
      use-basic-authentication-with-access-code-grant: on
authorization:
  issuer-uri: http://127.0.0.1:8080/mypass-manager/auth/
  success-logout-uri: http://127.0.0.1:8080/mypass-manager/auth/login
