spring:
  datasource:
    users:
      username: 'sa-authorization-server'
      password: 'P@sswordAuthS3rv3r'
      url: 'jdbc:postgresql://127.0.0.1:5432/db_users'
    auth:
      username: 'sa-authorization-server'
      password: 'P@sswordAuthS3rv3r'
      url: 'jdbc:postgresql://127.0.0.1:5432/db_auth'
  flyway:
    enabled: true
    user: 'sa-authorization-server'
    password: 'P@sswordAuthS3rv3r'
    schemas:
      - 'public'
    url: jdbc:postgresql://127.0.0.1:5432/db_auth
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: 'MHP@SSW0R3#20230401' # default no password, for set use SPRING_REDIS_PASSWORD or -Dspring.redis.password
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    virtual-host: vhost-password-manager
    username: authorization-server-pm
    password: authorization-server-pm-P@ss
management:
  endpoint:
    health:
      group:
        database:
          show-components: always
          show-details: always
          include:
            - db
            - redis
            - ping
            - rabbit
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'
springdoc:
  swagger-ui:
    oauth2-redirect-url: http://127.0.0.1:8080/mypass-manager/auth/swagger-ui/redirect
    csrf:
      enabled: true
