spring:
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: 'MHP@SSW0R3#20230401' # default no password, for set use SPRING_REDIS_PASSWORD or -Dspring.redis.password
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: vhost-password-manager
    username: email-service-pm
    password: email-service-pm-P@ss
  mail:
    host: 127.0.0.1
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: false
      mail.smtp.port: 1025
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8080/mypass-manager/auth/
application:
  email:
    type: mail
    default-sender: ${APPLICATION_EMAIL_DEFAULT_SENDER:no-reply@localhost.fake.mail.com}
    enable-redirect-mail: ${APPLICATION_EMAIL_ENABLE_REDIRECT_MAIL:false}
    address-redirect-mail: ${APPLICATION_EMAIL_ADDRESS_REDIRECT_MAIL:no-reply@localhost.fake.mail.com}
logging:
  level:
    br.com.marcoshssilva.mhpasswordmanager.emailservice.amqp.listeners:
      QueueSendConfirmationRegisteredUserListener: debug
      QueueSendRecoveryCode: debug
      QueueSendEmailListener: debug
management:
  endpoint:
    health:
      group:
        database:
          show-components: always
          show-details: always
          include:
            - redis
            - ping
            - rabbit
            - mail
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'metrics'
          - 'info'
springdoc:
  swagger-ui:
    oauth2-redirect-url: http://127.0.0.1:8080/mypass-manager/emails/swagger-ui/redirect
    csrf:
      enabled: true
